/*
目的：STAGEのデータファイルをテーブルにCOPYする
注意：1行でもエラーなら全体を失敗させる（ABORT_STATEMENT）
*/
COPY INTO OLIST_DWH.RAW.OLIST_CUSTOMERS_DATASET
  FROM @OLIST_STAGE
  FILES = ('olist_customers_dataset.csv.gz')
  FILE_FORMAT = (FORMAT_NAME = CSV_OLIST_FORMAT)
  ON_ERROR = ABORT_STATEMENT;   -- デフォルトだが手順書として明示	


COPY INTO OLIST_DWH.RAW.OLIST_GEOLOCATION_DATASET
  FROM @OLIST_STAGE
  FILES = ('olist_geolocation_dataset.csv.gz')
  FILE_FORMAT = (FORMAT_NAME = CSV_OLIST_FORMAT)
  ON_ERROR = ABORT_STATEMENT;   -- デフォルトだが手順書として明示


COPY INTO OLIST_DWH.RAW.OLIST_ORDER_ITEMS_DATASET
  FROM @OLIST_STAGE
  FILES = ('olist_order_items_dataset.csv.gz')
  FILE_FORMAT = (FORMAT_NAME = CSV_OLIST_FORMAT)
  ON_ERROR = ABORT_STATEMENT;   -- デフォルトだが手順書として明示


COPY INTO OLIST_DWH.RAW.OLIST_ORDER_PAYMENTS_DATASET
  FROM @OLIST_STAGE
  FILES = ('olist_order_payments_dataset.csv.gz')
  FILE_FORMAT = (FORMAT_NAME = CSV_OLIST_FORMAT)
  ON_ERROR = ABORT_STATEMENT;   -- デフォルトだが手順書として明示


COPY INTO OLIST_DWH.RAW.OLIST_ORDER_REVIEWS_DATASET
  FROM @OLIST_STAGE
  FILES = ('olist_order_reviews_dataset.csv.gz')
  FILE_FORMAT = (FORMAT_NAME = CSV_OLIST_FORMAT)
  ON_ERROR = ABORT_STATEMENT;   -- デフォルトだが手順書として明示


COPY INTO OLIST_DWH.RAW.OLIST_ORDERS_DATASET
  FROM @OLIST_STAGE
  FILES = ('olist_orders_dataset.csv.gz')
  FILE_FORMAT = (FORMAT_NAME = CSV_OLIST_FORMAT)
  ON_ERROR = ABORT_STATEMENT;   -- デフォルトだが手順書として明示


COPY INTO OLIST_DWH.RAW.OLIST_PRODUCTS_DATASET
  FROM @OLIST_STAGE
  FILES = ('olist_products_dataset.csv.gz')
  FILE_FORMAT = (FORMAT_NAME = CSV_OLIST_FORMAT)
  ON_ERROR = ABORT_STATEMENT;   -- デフォルトだが手順書として明示


COPY INTO OLIST_DWH.RAW.OLIST_SELLERS_DATASET
  FROM @OLIST_STAGE
  FILES = ('olist_sellers_dataset.csv.gz')
  FILE_FORMAT = (FORMAT_NAME = CSV_OLIST_FORMAT)
  ON_ERROR = ABORT_STATEMENT;   -- デフォルトだが手順書として明示


COPY INTO OLIST_DWH.RAW.PRODUCT_CATEGORY_NAME_TRANSLATION
  FROM @OLIST_STAGE
  FILES = ('product_category_name_translation.csv.gz')
  FILE_FORMAT = (FORMAT_NAME = CSV_OLIST_FORMAT)
  ON_ERROR = ABORT_STATEMENT;   -- デフォルトだが手順書として明示
