/*
目的：COPY後の件数確認
注意：事前調査した件数と一致しているかを確認する（data_profiling.md）
*/
SELECT 'OLIST_CUSTOMERS_DATASET' AS table_name, COUNT(*) AS row_count FROM OLIST_DWH.RAW.OLIST_CUSTOMERS_DATASET
UNION ALL
SELECT 'OLIST_ORDERS_DATASET', COUNT(*) FROM OLIST_DWH.RAW.OLIST_ORDERS_DATASET
UNION ALL
SELECT 'OLIST_GEOLOCATION_DATASET', COUNT(*) FROM OLIST_DWH.RAW.OLIST_GEOLOCATION_DATASET
UNION ALL
SELECT 'OLIST_ORDER_ITEMS_DATASET', COUNT(*) FROM OLIST_DWH.RAW.OLIST_ORDER_ITEMS_DATASET
UNION ALL
SELECT 'OLIST_ORDER_PAYMENTS_DATASET', COUNT(*) FROM OLIST_DWH.RAW.OLIST_ORDER_PAYMENTS_DATASET
UNION ALL
SELECT 'OLIST_ORDER_REVIEWS_DATASET', COUNT(*) FROM OLIST_DWH.RAW.OLIST_ORDER_REVIEWS_DATASET
UNION ALL
SELECT 'OLIST_PRODUCTS_DATASET', COUNT(*) FROM OLIST_DWH.RAW.OLIST_PRODUCTS_DATASET
UNION ALL
SELECT 'OLIST_SELLERS_DATASET', COUNT(*) FROM OLIST_DWH.RAW.OLIST_SELLERS_DATASET
UNION ALL
SELECT 'PRODUCT_CATEGORY_NAME_TRANSLATION', COUNT(*) FROM OLIST_DWH.RAW.PRODUCT_CATEGORY_NAME_TRANSLATION
ORDER BY table_name;
